### ISSUE TITLE
Support Scala.JS

### ISSUE THREAD

**Issue by mdedetrich** [melezov/scala-uuid#2]
Any plans to add support for Scala.js? It should be fairly trivial since Scala.js has support for `java.util.UUID` as well (i.e. https://github.com/scala-js/scala-js/blob/master/javalib/src/main/scala/java/util/UUID.scala)

If there are no objections, I can add support via a pull request

**Comment by melezov** [comment]
PRs are welcome, but the main reason I have a problem with this is that this entire optimised wrapper uses very delicate integer math which will be hard / impossible to reproduce in JS. Even the notion of UUID being represented by two Longs simply cannot be translated into JS.

As I see it, the only way to proceed with this would be to create a completely separate Scala for JS repository, which defeats the purpose of this library.

**Comment by mdedetrich** [comment]
I actually tried working on this and I have come up with my solutions, also Scala.js does support the integer/long based math but it is definitely harder than I anticipated (and it would require different modules to work)
