### ISSUE TITLE
Build for 2.13.0

### ISSUE THREAD

**Issue by ryanberckmans** [melezov/scala-uuid#4]
I think right now scala-uuid might be built only to scala 2.13.0-M5, not 2.13.0

https://mvnrepository.com/artifact/io.jvm.uuid/scala-uuid

Great library, thanks!

**Comment by ryanberckmans** [comment]
https://github.com/melezov/scala-uuid/pull/5

**Comment by melezov** [comment]
Thanks, merging.

**Comment by melezov** [comment]
Hey @ryanberckmans, I've published 0.3.1 for 2.13.0 to Sonatype OSS - it should be available in an hour or so.

**Comment by ryanberckmans** [comment]
Thanks! Love scala-uuid, I use it a lot.
