### ISSUE TITLE
Add scaladoc link

### ISSUE THREAD

**Issue by ryanberckmans** [melezov/scala-uuid#6]
Is there a scaladoc link? If not, it'd be great to have one. Thanks!

**Comment by melezov** [comment]
Yo, the scaladoc link is available on each branche's README.md by clicking the scaladoc banner.

Here's a direct link for your convenience:
https://oss.sonatype.org/service/local/repositories/releases/archive/io/jvm/uuid/scala-uuid_2.13/0.3.1/scala-uuid_2.13-0.3.1-javadoc.jar/!/io/jvm/uuid/index.html

**Comment by melezov** [comment]
![linky](https://user-images.githubusercontent.com/551485/83535111-e8ead880-a4f1-11ea-9f35-2503b9b16744.PNG)
